#!/bin/bash
commit_msg=$(cat "${1}")
hotfix_msg='A corregir por:'

if git branch -a | grep "*" | grep "hotfix"; then
        if [[ "$commit_msg" == *"$hotfix_msg"* ]]; then
                exit 0
        else 
                echo "El mensaje debe contener -> A corregir por:"
                exit 1
        fi
fi